sudo: required
services:
  - docker

before_install:
  - docker build -t nongod/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run nongod/react-test npm test -- --coverage

after_success:
  - docker build -t nongod/multi-client ./client
  - docker build -t nongod/multi-nginx ./nginx
  - docker build -t nongod/multi-server ./server
  - docker build -t nongod/multi-worker ./worker
  # Log in to tth docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push nongod/multi-client
  - docker push nongod/multi-nginx
  - docker push nongod/multi-server
  - docker push nongod/multi-worker
  